import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { LockClosedIcon } from '@heroicons/react/solid'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <div>Dashboard</div>
          <div>UserIcon</div>
        </header>
        <h1 className="text-3xl font-bold underline">
          Welcome UserX
        </h1>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Button 1 &rarr;</h2>
            <p>Ação 1</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Button 2 &rarr;</h2>
            <p>Ação 2</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >Feito por Clebinho Cebolinha Arroba</a>
      </footer>
    </div>
  )
}
